version: '3.7'
services:

  redis:
    # contains redis server and redis insight GUI client
    image: redis/redis-stack:latest
    ports:
      - '6379:6379'
      - '8001:8001'
    environment:
      REDIS_ARGS: '--save 20 1 --loglevel warning --requirepass redispassword'

  wiremock:
    image: rodolpheche/wiremock
    container_name: wiremock
    command: "--global-response-templating --verbose"
    ports:
      - "9001:8080"
    volumes:
      - ./wiremock/__files:/home/wiremock/__files
      - ./wiremock/mappings:/home/wiremock/mappings