spring:
  jackson:
    serialization:
      write_dates_as_timestamps: false

cache:
  redis:
    host: localhost
    port: 6379
    password: redispassword
    ttl-minutes: 5

external-api:
  url: http://localhost:9001
  user-agent: spring-webflux-poc
  api-key: abcdefghijklmnop
  timeout-millis: 5000
  user-path: /api/v3/users/{userId}
  reservations-path: /api/v3/users/{userId}/reservations
  payment-history-path: /api/v3/users/{userId}/payments

logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    org.springframework.cache: TRACE
    reactor.netty.http.client: DEBUG
    root: INFO
